import { Trip } from "./trip-types";

export interface ExportOptions {
  includeFrontmatter: boolean;
  includeSummary: boolean;
  includeSamples: boolean;
  notes?: string;
}

export function generateTripMarkdown(trip: Trip, options: ExportOptions): string {
  const lines: string[] = [];

  // YAML Frontmatter
  if (options.includeFrontmatter) {
    lines.push("---");
    lines.push("type: obd_trip");
    if (trip.metadata.vehicle) {
      lines.push(`vehicle: "${trip.metadata.vehicle}"`);
    }
    lines.push(`start: ${new Date(trip.metadata.startTime).toISOString()}`);
    if (trip.metadata.endTime) {
      lines.push(`end: ${new Date(trip.metadata.endTime).toISOString()}`);
    }
    lines.push(`duration_sec: ${trip.stats.durationSec}`);
    lines.push(`distance_mi: ${trip.stats.distanceMi.toFixed(2)}`);
    lines.push(`fuel_start_pct: ${trip.stats.fuelStartPct.toFixed(1)}`);
    lines.push(`fuel_end_pct: ${trip.stats.fuelEndPct.toFixed(1)}`);
    lines.push(`fuel_used_pct: ${trip.stats.fuelUsedPct.toFixed(1)}`);
    lines.push(`avg_speed_mph: ${trip.stats.avgSpeedMph.toFixed(1)}`);
    lines.push(`max_speed_mph: ${trip.stats.maxSpeedMph.toFixed(1)}`);
    lines.push(`avg_rpm: ${Math.round(trip.stats.avgRpm)}`);
    lines.push(`max_rpm: ${Math.round(trip.stats.maxRpm)}`);
    lines.push(`avg_coolant_f: ${trip.stats.avgCoolantF.toFixed(1)}`);
    lines.push(`max_coolant_f: ${trip.stats.maxCoolantF.toFixed(1)}`);
    lines.push(`max_load_pct: ${trip.stats.maxLoadPct.toFixed(1)}`);
    lines.push(`idle_time_sec: ${trip.stats.idleTimeSec}`);
    lines.push(`recording_mode: ${trip.metadata.recordingMode}`);
    lines.push(`status: ${trip.metadata.status}`);
    lines.push("---");
    lines.push("");
  }

  // Title
  const startDate = new Date(trip.metadata.startTime);
  lines.push(`# Trip - ${startDate.toLocaleDateString()} ${startDate.toLocaleTimeString()}`);
  lines.push("");

  // Summary Table
  if (options.includeSummary) {
    lines.push("## Summary");
    lines.push("");
    lines.push("| Metric | Value |");
    lines.push("|--------|-------|");
    lines.push(`| **Duration** | ${formatDuration(trip.stats.durationSec)} |`);
    lines.push(`| **Distance** | ${trip.stats.distanceMi.toFixed(2)} mi |`);
    lines.push(`| **Fuel Used** | ${trip.stats.fuelUsedPct.toFixed(1)}% (${trip.stats.fuelStartPct.toFixed(1)}% → ${trip.stats.fuelEndPct.toFixed(1)}%) |`);
    lines.push(`| **Avg Speed** | ${trip.stats.avgSpeedMph.toFixed(1)} mph |`);
    lines.push(`| **Max Speed** | ${trip.stats.maxSpeedMph.toFixed(1)} mph |`);
    lines.push(`| **Avg RPM** | ${Math.round(trip.stats.avgRpm)} rpm |`);
    lines.push(`| **Max RPM** | ${Math.round(trip.stats.maxRpm)} rpm |`);
    lines.push(`| **Avg Coolant** | ${trip.stats.avgCoolantF.toFixed(1)}°F |`);
    lines.push(`| **Max Coolant** | ${trip.stats.maxCoolantF.toFixed(1)}°F |`);
    lines.push(`| **Max Load** | ${trip.stats.maxLoadPct.toFixed(1)}% |`);
    lines.push(`| **Idle Time** | ${formatDuration(trip.stats.idleTimeSec)} |`);
    lines.push(`| **Recording Mode** | ${trip.metadata.recordingMode} |`);
    lines.push(`| **Status** | ${trip.metadata.status} |`);
    lines.push("");
  }

  // Notes
  const notesToInclude = options.notes || trip.notes;
  if (notesToInclude) {
    lines.push("## Notes");
    lines.push("");
    lines.push(notesToInclude);
    lines.push("");
  }

  // Samples
  if (options.includeSamples && trip.samples.length > 0) {
    lines.push("## Samples");
    lines.push("");
    lines.push("| Time | Speed (mph) | RPM | Coolant (°F) | Load (%) | Fuel (%) |");
    lines.push("|------|-------------|-----|--------------|----------|----------|");
    
    // Include every Nth sample to keep table manageable (max 20 rows)
    const maxSamples = 20;
    const step = Math.max(1, Math.floor(trip.samples.length / maxSamples));
    
    for (let i = 0; i < trip.samples.length; i += step) {
      const sample = trip.samples[i];
      const elapsed = Math.floor((sample.timestamp - trip.metadata.startTime) / 1000);
      lines.push(
        `| ${formatDuration(elapsed)} | ${sample.speedMph.toFixed(1)} | ${Math.round(sample.rpm)} | ${sample.coolantF.toFixed(1)} | ${sample.engineLoadPercent.toFixed(1)} | ${sample.fuelPercent.toFixed(1)} |`
      );
    }
    lines.push("");
  }

  // Footer
  lines.push("---");
  lines.push(`*Generated by SonataOBD on ${new Date().toLocaleString()}*`);

  return lines.join("\n");
}

function formatDuration(seconds: number): string {
  const hours = Math.floor(seconds / 3600);
  const minutes = Math.floor((seconds % 3600) / 60);
  const secs = seconds % 60;

  if (hours > 0) {
    return `${hours}h ${minutes}m ${secs}s`;
  } else if (minutes > 0) {
    return `${minutes}m ${secs}s`;
  } else {
    return `${secs}s`;
  }
}

export function generateTripFilename(trip: Trip): string {
  const startDate = new Date(trip.metadata.startTime);
  const dateStr = startDate.toISOString().split("T")[0]; // YYYY-MM-DD
  const timeStr = startDate.toTimeString().split(" ")[0].replace(/:/g, "-"); // HH-MM-SS
  return `trip_${dateStr}_${timeStr}.md`;
}
