package tech.vasker.vector.trip

import java.io.File
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

fun generateTripMarkdown(
    metadata: TripMetadata,
    stats: TripStats,
    includeSamples: Boolean,
    tripDir: File,
): String {
    val startIso = TripStorage.formatIso(metadata.startTime)
    val endIso = metadata.endTime?.let { TripStorage.formatIso(it) } ?: ""
    val titleDate = SimpleDateFormat("MMM d, yyyy h:mm a", Locale.getDefault()).format(Date(metadata.startTime))
    val footerDate = SimpleDateFormat("MMM d, yyyy", Locale.getDefault()).format(Date())

    val sb = StringBuilder()
    sb.appendLine("---")
    sb.appendLine("type: obd_trip")
    sb.appendLine("start: $startIso")
    if (endIso.isNotEmpty()) sb.appendLine("end: $endIso")
    sb.appendLine("duration_sec: ${stats.durationSec}")
    sb.appendLine("distance_mi: ${formatDouble(stats.distanceMi)}")
    sb.appendLine("fuel_start_pct: ${formatNullable(stats.fuelStartPct)}")
    sb.appendLine("fuel_end_pct: ${formatNullable(stats.fuelEndPct)}")
    sb.appendLine("fuel_used_pct: ${formatNullable(stats.fuelUsedPct)}")
    sb.appendLine("avg_speed_mph: ${formatDouble(stats.avgSpeedMph)}")
    sb.appendLine("max_speed_mph: ${formatDouble(stats.maxSpeedMph)}")
    sb.appendLine("avg_rpm: ${formatDouble(stats.avgRpm)}")
    sb.appendLine("max_rpm: ${formatDouble(stats.maxRpm)}")
    sb.appendLine("avg_coolant_f: ${formatDouble(stats.avgCoolantF)}")
    sb.appendLine("max_coolant_f: ${formatDouble(stats.maxCoolantF)}")
    sb.appendLine("max_load_pct: ${formatDouble(stats.maxLoadPct)}")
    sb.appendLine("idle_time_sec: ${stats.idleTimeSec}")
    sb.appendLine("recording_mode: ${metadata.recordingMode.name.lowercase()}")
    sb.appendLine("status: ${metadata.status.name.lowercase()}")
    metadata.endReason?.let { sb.appendLine("end_reason: $it") }
    sb.appendLine("---")
    sb.appendLine()
    sb.appendLine("# Trip - $titleDate")
    sb.appendLine()
    sb.appendLine("## Summary")
    sb.appendLine()
    sb.appendLine("| Field | Value |")
    sb.appendLine("| --- | --- |")
    sb.appendLine("| Duration | ${formatDuration(stats.durationSec)} |")
    sb.appendLine("| Distance | ${formatDouble(stats.distanceMi)} mi |")
    sb.appendLine("| Fuel Used | ${formatNullable(stats.fuelUsedPct)}% |")
    sb.appendLine("| Avg Speed | ${formatDouble(stats.avgSpeedMph)} mph |")
    sb.appendLine("| Max Speed | ${formatDouble(stats.maxSpeedMph)} mph |")
    sb.appendLine("| Avg RPM | ${formatDouble(stats.avgRpm)} |")
    sb.appendLine("| Max RPM | ${formatDouble(stats.maxRpm)} |")
    sb.appendLine("| Avg Coolant | ${formatDouble(stats.avgCoolantF)} F |")
    sb.appendLine("| Max Coolant | ${formatDouble(stats.maxCoolantF)} F |")
    sb.appendLine("| Max Load | ${formatDouble(stats.maxLoadPct)}% |")
    sb.appendLine("| Idle Time | ${stats.idleTimeSec} sec |")
    sb.appendLine("| Recording Mode | ${metadata.recordingMode.name.lowercase()} |")
    sb.appendLine("| Status | ${metadata.status.name.lowercase()} |")

    if (includeSamples) {
        val samplesFile = File(tripDir, "samples.csv")
        if (samplesFile.exists()) {
            sb.appendLine()
            sb.appendLine("## Samples")
            sb.appendLine()
            sb.appendLine("| Time | Speed | RPM | Coolant | Load | Fuel |")
            sb.appendLine("| --- | --- | --- | --- | --- | --- |")
            samplesFile.readLines().drop(1).forEach { line ->
                val parts = line.split(",")
                if (parts.size < 9) return@forEach
                val time = parts[1]
                val speed = parts[2].ifEmpty { "—" }
                val rpm = parts[3].ifEmpty { "—" }
                val coolant = parts[5].ifEmpty { "—" }
                val load = parts[6].ifEmpty { "—" }
                val fuel = parts[4].ifEmpty { "—" }
                sb.appendLine("| $time | $speed | $rpm | $coolant | $load | $fuel |")
            }
        }
    }

    sb.appendLine()
    sb.appendLine("*Generated by Talon on $footerDate*")
    return sb.toString()
}

private fun formatDouble(value: Double): String = String.format(Locale.US, "%.1f", value)

private fun formatNullable(value: Double?): String = value?.let { formatDouble(it) } ?: "—"

private fun formatDuration(seconds: Int): String {
    val hours = seconds / 3600
    val minutes = (seconds % 3600) / 60
    return if (hours > 0) "${hours}h ${minutes}m" else "${minutes}m"
}
