package tech.vasker.vector.trip

import java.io.File
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

fun generateTripMarkdown(
    metadata: TripMetadata,
    stats: TripStats,
    includeSamples: Boolean,
    tripDir: File,
): String {
    val startIso = TripStorage.formatIso(metadata.startTime)
    val endIso = metadata.endTime?.let { TripStorage.formatIso(it) } ?: ""
    val titleDate = SimpleDateFormat("MMM d, yyyy h:mm a", Locale.getDefault()).format(Date(metadata.startTime))
    val footerDate = SimpleDateFormat("MMM d, yyyy", Locale.getDefault()).format(Date())

    val sb = StringBuilder()
    sb.appendLine("---")
    sb.appendLine("type: obd_trip")
    sb.appendLine("start: $startIso")
    if (endIso.isNotEmpty()) sb.appendLine("end: $endIso")
    sb.appendLine("duration_sec: ${stats.durationSec}")
    sb.appendLine("distance_mi: ${formatDistanceMi(stats.distanceMi)}")
    sb.appendLine("distance_miles: ${formatDistanceMi(stats.distanceMi)}")
    sb.appendLine("fuel_start_pct: ${formatNullable(stats.fuelStartPct)}")
    sb.appendLine("fuel_end_pct: ${formatNullable(stats.fuelEndPct)}")
    sb.appendLine("fuel_used_pct: ${formatNullable(stats.fuelUsedPct)}")
    sb.appendLine("fuel_burned_gal: ${formatNullableFuelGal(stats.fuelBurnedGal)}")
    sb.appendLine("fuel_used_gallons: ${formatNullableFuelGal(stats.fuelBurnedGal)}")
    stats.avgFuelBurnGph?.let { sb.appendLine("avg_fuel_burn_gph: ${formatDouble(it)}") }
    stats.fuelMethod?.let { sb.appendLine("fuel_method: $it") }
    val mpg = if (stats.fuelBurnedGal != null && stats.fuelBurnedGal!! > 0 && stats.distanceMi > 0)
        stats.distanceMi / stats.fuelBurnedGal!! else null
    mpg?.let { sb.appendLine("mpg: ${formatDouble(it)}") }
    sb.appendLine("status: ${metadata.status.name.lowercase()}")
    sb.appendLine("---")
    sb.appendLine()
    sb.appendLine("# Trip - $titleDate")
    sb.appendLine()
    sb.appendLine("## Summary")
    sb.appendLine()
    sb.appendLine("| Field | Value |")
    sb.appendLine("| --- | --- |")
    sb.appendLine("| Duration | ${formatDuration(stats.durationSec)} |")
    sb.appendLine("| Distance | ${formatDistanceMi(stats.distanceMi)} mi |")
    sb.appendLine("| Fuel Used | ${formatNullable(stats.fuelUsedPct)}% |")
    sb.appendLine("| Fuel Burned | ${formatNullableFuelGal(stats.fuelBurnedGal)} gal |")
    sb.appendLine("| MPG | ${mpg?.let { formatDouble(it) } ?: "—"} |")
    sb.appendLine("| Status | ${metadata.status.name.lowercase()} |")

    if (includeSamples) {
        val samplesFile = File(tripDir, "samples.csv")
        if (samplesFile.exists()) {
            sb.appendLine()
            sb.appendLine("## Samples")
            sb.appendLine()
            sb.appendLine("| Time | Speed | RPM | Coolant | Load | Fuel |")
            sb.appendLine("| --- | --- | --- | --- | --- | --- |")
            samplesFile.readLines().drop(1).forEach { line ->
                val parts = line.split(",")
                if (parts.size < 9) return@forEach
                val time = parts[1]
                val speed = parts[2].ifEmpty { "—" }
                val rpm = parts[3].ifEmpty { "—" }
                val coolant = parts[5].ifEmpty { "—" }
                val load = parts[6].ifEmpty { "—" }
                val fuel = parts[4].ifEmpty { "—" }
                sb.appendLine("| $time | $speed | $rpm | $coolant | $load | $fuel |")
            }
        }
    }

    sb.appendLine()
    sb.appendLine("*Generated by Talon on $footerDate*")
    return sb.toString()
}

private fun formatDouble(value: Double): String = String.format(Locale.US, "%.1f", value)

private fun formatMiles(value: Double): String = String.format(Locale.US, "%.2f", value)

/** Distance miles: 3 decimals so small values (e.g. 0.01 mi) are visible in export. */
private fun formatDistanceMi(value: Double): String = String.format(Locale.US, "%.3f", value)

/** Fuel gallons: 3 decimals so small values (e.g. 0.01) are visible. */
private fun formatFuelGal(value: Double): String = String.format(Locale.US, "%.3f", value)

private fun formatNullable(value: Double?): String = value?.let { formatDouble(it) } ?: "—"

private fun formatNullableFuelGal(value: Double?): String = value?.let { formatFuelGal(it) } ?: "—"

private fun formatDuration(seconds: Int): String {
    val hours = seconds / 3600
    val minutes = (seconds % 3600) / 60
    return if (hours > 0) "${hours}h ${minutes}m" else "${minutes}m"
}
